name: car_free_company
description: A Car Free Company Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  fish_redux: ^0.1.7
  event_bus: ^1.1.0
  shared_preferences: ^0.5.1+2
  dio: ^2.1.0
  connectivity: ^0.4.2+2
  flutter_spinkit: ^3.1.0
  fluttertoast: ^3.0.3
  flutter_statusbar: ^0.0.1
  url_launcher: ^5.0.2
  rxdart: ^0.21.0
  provide: ^1.0.2
  flutter_picker: ^1.0.10
  json_annotation: ^2.2.0
  flutter_local_notifications: ^0.5.2
  animated_floatactionbuttons: ^0.1.0
  package_info: ^0.4.0+2
  pub_semver: ^1.4.2
  qr_flutter: ^2.0.0
  common_utils: ^1.1.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable:


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - lib/static/images/user.ico
  - lib/static/images/welcome01.jpg
  - lib/static/images/loginbackground.jpeg
  - lib/static/images/ic_arrow_right.png
  - lib/static/images/userformy02.ico
  - lib/static/images/historybill.ico
  - lib/static/images/cancelqueue.ico
  - lib/static/images/dailysourceplan.ico
  - lib/static/images/dispatcheh.ico
  - lib/static/images/driverquery.ico
  - lib/static/images/vehiclequery.ico
  - lib/static/images/vehiclequeue.ico
  - lib/static/images/message.ico
  - lib/static/images/dailyplan.ico
  - lib/static/images/driver.ico
  - lib/static/images/vehiclequerysub.ico
  - lib/static/images/driverquerysub.ico
  - lib/static/images/historybillsub.ico
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
